# CC = g++
# EXEC: test

# all: ${EXEC} : instancia.o solucao.o csv.o main.o
# 	${CC} -o test instancia.o solucao.o csv.o main.o

# Instancia.o: ../src/cpp/instancia/instancia.cpp
# 	${CC} -o instancia.o -c ../src/cpp/instancia/instancia.cpp

# Instancia.o: ../src/cpp/engine/instancia.cpp
# 	${CC} -o instancia.o -c ../src/cpp/engine/instancia.cpp

# Solucao.o: ../src/cpp/engine/solucao.cpp
# 	${CC} -o solucao.o -c ../src/cpp/engine/solucao.cpp

# CSV.o: ../src/cpp/helpers/csv.cpp
# 	${CC} -o instancia.o -c ../src/cpp/helpers/csv.cpp

# Main.o: ../src/cpp/instancia/instancia.cpp
# 	${CC} -o main.o -cmain.cpp

# Clean:
# 	rm -rf *.o

hello:
	echo "Teste"