#include <string>
#include <iostream>
#include <iterator>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <list>
#include <array>
#include <cstring>
#include <iomanip>